---
abstract: "perldoc that works for modules you don't have installed"
author:
  - 'Shawn M Moore C<sartak@gmail.com> (original implementation)'
build_requires:
  ExtUtils::MakeMaker: 6.62
configure_requires:
  ExtUtils::MakeMaker: 6.62
distribution_type: module
dynamic_config: 1
generated_by: 'Module::Install version 1.04'
license: perl
meta-spec:
  url: http://module-build.sourceforge.net/META-spec-v1.4.html
  version: 1.4
name: Pod-Minicpandoc
no_index:
  directory:
    - inc
requires:
  Archive::Tar: 0
  Archive::Zip: 0
  File::Spec: 0
  HTTP::Tiny: 0
  IO::Uncompress::Gunzip: 0
  perl: 5.8.1
resources:
  homepage: https://github.com/hoelzro/pod-minicpandoc
  license: http://dev.perl.org/licenses/
  repository:
    type: git
    url: git://github.com/hoelzro/pod-minicpandoc
    web: https://github.com/hoelzro/pod-minicpandoc
version: 0.11
